site_name: FloodForge Documentation
site_url: https://haizlbliek.github.io/FloodForge-Docs/

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo

docs_dir: docs/